# Error handling, "try...catch"  

https://javascript.info/try-catch  
The try...catch construct allows to handle runtime errors. It literally allows to “try” running the code and “catch” errors that may occur in it.

The try...catch construct may have one more code clause: finally.  
If it exists, it runs in all cases:  
after try, if there were no errors,  
after catch, if there were errors.

![Screenshot_37](https://user-images.githubusercontent.com/66359081/161568766-3ef84b8a-c798-414e-b27f-127b92e2b7d6.png)

